version: "3.8"

services:
  commander:
    image: scrapoxy/scrapoxy
    command: "node scrapoxy.js start -f -c --storage file"
    ports:
      - 8890:8890
    environment:
      - NODE_ENV=production
      - AUTH_LOCAL_USERNAME=${AUTH_LOCAL_USERNAME}  # Placeholder for username
      - AUTH_LOCAL_PASSWORD=${AUTH_LOCAL_PASSWORD}  # Placeholder for password
      - BACKEND_JWT_SECRET=${BACKEND_JWT_SECRET}  # Placeholder for JWT secret
      - BACKEND_JWT_EXPIRATION=60s
      - FRONTEND_JWT_SECRET=${FRONTEND_JWT_SECRET}  # Placeholder for JWT secret
      - FRONTEND_JWT_EXPIRATION=24h
      - FRONTEND_SECURE_COOKIE=0
      - COMMANDER_PORT=8890
      - COMMANDER_URL=${COMMANDER_FQDN}/api  # Placeholder for FQDN
      - FRONTEND_URL=${COMMANDER_FQDN}  # Placeholder for FQDN
      - STORAGE_FILE_FILENAME=/etc/scrapoxy/config.json
      - STORAGE_FILE_CERTIFICATES_MAX=1000
      - CLEAR_AT_SHUTDOWN=0
      - STOPPING_DELAY=2000
    volumes:
      - ./scrapoxy:/etc/scrapoxy
    deploy:
      resources:
        limits:
          cpus: "1.0"
        reservations:
          cpus: "0.5"

  haproxy:
    image: haproxy
    ports:
      - 8888:8888
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  master:
    image: scrapoxy/scrapoxy
    command: "node scrapoxy.js start -m"
    deploy:
      mode: replicated
      replicas: 2  # Number of Master instances
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "1.0"
        reservations:
          cpus: "0.5"
    environment:
      - NODE_ENV=production
      - COMMANDER_URL=${COMMANDER_FQDN}/api  # Placeholder for FQDN
      - BACKEND_JWT_SECRET=${BACKEND_JWT_SECRET}  # Placeholder for JWT secret
      - MASTER_PORT=8888
      - MASTER_TIMEOUT=60000
      - MASTER_CERTIFICATE_CERT=
      - MASTER_CERTIFICATE_KEY=
    depends_on:
      - commander

  refresh:
    image: scrapoxy/scrapoxy
    command: "node scrapoxy.js start -r"
    environment:
      - NODE_ENV=production
      - COMMANDER_URL=${COMMANDER_FQDN}/api  # Placeholder for FQDN
      - BACKEND_JWT_SECRET=${BACKEND_JWT_SECRET}  # Placeholder for JWT secret
      - PROBE_PORT=8887
      - FINGERPRINT_URL=https://fingerprint.scrapoxy.io/api/json
      - FINGERPRINT_FOLLOW_REDIRECT_MAX=3
      - FINGERPRINT_RETRY_MAX=2
      - FINGERPRINT_TIMEOUT=5000
      - CONNECTORS_REFRESH_EMPTY_DELAY=1000
      - CONNECTORS_REFRESH_ERROR_DELAY=2000
      - PROXY_REFRESH_COUNT=200
      - PROXY_REFRESH_DELAY=1000
      - PROXIES_REFRESH_EMPTY_DELAY=1000
      - PROXIES_REFRESH_ERROR_DELAY=2000
      - FREEPROXY_REFRESH_COUNT=100
      - FREEPROXY_REFRESH_DELAY=60000
      - FREEPROXIES_REFRESH_EMPTY_DELAY=1000
      - FREEPROXIES_REFRESH_ERROR_DELAY=2000
      - MASTER_REFRESH_METRICS_DELAY=10000
      - METRICS_REFRESH_REFRESH_DELAY=10000
      - TASKS_REFRESH_EMPTY_DELAY=1000
      - TASKS_REFRESH_ERROR_DELAY=2000
    depends_on:
      - commander
    deploy:
      resources:
        limits:
          cpus: "1.0"
        reservations:
          cpus: "0.5"
